language: ruby
rvm:
  - 1.9.3
  - 2.1.1
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_install: cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - export RAILS_ENV=test
  - rake db:setup
