sqlite: &sqlite
  adapter: sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  password:

postgresql: &postgresql
  adapter: postgresql
  database: travis_ci_test
  username: postgres

defaults: &defaults
  database: db/<%= ENV['RAILS_ENV'] %>
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || 'sqlite' %>

development:
  <<: *defaults

test:
  <<: *defaults
