defaults: &defaults
  adapter: mysql2
  username: root
  password:
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: db/development.sqlite3

test:
  <<: *defaults
  database: db/test.sqlite3
